package net.vacaciones.entity;
// Generated Feb 7, 2018 10:33:40 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PasswordResets generated by hbm2java
 */
@Entity
@Table(name = "password_resets", catalog = "vacaciones")
public class PasswordResets implements java.io.Serializable {

	private PasswordResetsId id;

	public PasswordResets() {
	}

	public PasswordResets(PasswordResetsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "email", column = @Column(name = "email", nullable = false)),
			@AttributeOverride(name = "token", column = @Column(name = "token", nullable = false)),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", nullable = false, length = 19)) })
	public PasswordResetsId getId() {
		return this.id;
	}

	public void setId(PasswordResetsId id) {
		this.id = id;
	}

}
