package net.vacaciones.entity;
// Generated Feb 7, 2018 8:51:06 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PasswordResetsId generated by hbm2java
 */
@Embeddable
public class PasswordResetsId implements java.io.Serializable {

	private String email;
	private String token;
	private Date createdAt;

	public PasswordResetsId() {
	}

	public PasswordResetsId(String email, String token, Date createdAt) {
		this.email = email;
		this.token = token;
		this.createdAt = createdAt;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "token", nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasswordResetsId))
			return false;
		PasswordResetsId castOther = (PasswordResetsId) other;

		return ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null && castOther.getEmail() != null
				&& this.getEmail().equals(castOther.getEmail())))
				&& ((this.getToken() == castOther.getToken()) || (this.getToken() != null
						&& castOther.getToken() != null && this.getToken().equals(castOther.getToken())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getToken() == null ? 0 : this.getToken().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		return result;
	}

}
