package net.vacaciones.entity;
// Generated Feb 10, 2018 5:19:38 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacations generated by hbm2java
 */
@Entity
@Table(name = "vacations", catalog = "vacaciones")
public class Vacations implements java.io.Serializable {

	private Integer id;
	private String observations;
	private String type;
	private Date createdAt;
	private Date updatedAt;
	private Date dateFrom;
	private Date dateTo;
	private Integer daysTaken;
	private Integer acepted;

	public Vacations() {
	}

	public Vacations(String observations, String type, Date createdAt, Date updatedAt) {
		this.observations = observations;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Vacations(String observations, String type, Date createdAt, Date updatedAt, Date dateFrom, Date dateTo,
			Integer daysTaken, Integer acepted) {
		this.observations = observations;
		this.type = type;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.daysTaken = daysTaken;
		this.acepted = acepted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "observations", nullable = false)
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_to", length = 10)
	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	@Column(name = "days_taken")
	public Integer getDaysTaken() {
		return this.daysTaken;
	}

	public void setDaysTaken(Integer daysTaken) {
		this.daysTaken = daysTaken;
	}

	@Column(name = "acepted")
	public Integer getAcepted() {
		return this.acepted;
	}

	public void setAcepted(Integer acepted) {
		this.acepted = acepted;
	}

}
