package net.vacaciones.entity;
// Generated Feb 7, 2018 10:33:40 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workers generated by hbm2java
 */
@Entity
@Table(name = "workers", catalog = "vacaciones")
public class Workers implements java.io.Serializable {

	private Integer id;
	private Areas areas;
	private String name;
	private Date dateIn;
	private Date dateOut;
	private String position;
	private String email;
	private String reasonRetirement;
	private Date createdAt;
	private Date updatedAt;
	private Integer state;
	private Set<Vacations> vacationses = new HashSet<Vacations>(0);

	public Workers() {
	}

	public Workers(Areas areas, String name, Date dateIn, Date dateOut, String position, String email) {
		this.areas = areas;
		this.name = name;
		this.dateIn = dateIn;
		this.dateOut = dateOut;
		this.position = position;
		this.email = email;
	}

	public Workers(Areas areas, String name, Date dateIn, Date dateOut, String position, String email,
			String reasonRetirement, Date createdAt, Date updatedAt, Integer state, Set<Vacations> vacationses) {
		this.areas = areas;
		this.name = name;
		this.dateIn = dateIn;
		this.dateOut = dateOut;
		this.position = position;
		this.email = email;
		this.reasonRetirement = reasonRetirement;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.state = state;
		this.vacationses = vacationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public Areas getAreas() {
		return this.areas;
	}

	public void setAreas(Areas areas) {
		this.areas = areas;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_in", nullable = false, length = 10)
	public Date getDateIn() {
		return this.dateIn;
	}

	public void setDateIn(Date dateIn) {
		this.dateIn = dateIn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_out", nullable = false, length = 10)
	public Date getDateOut() {
		return this.dateOut;
	}

	public void setDateOut(Date dateOut) {
		this.dateOut = dateOut;
	}

	@Column(name = "position", nullable = false)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "reason_retirement", length = 65535)
	public String getReasonRetirement() {
		return this.reasonRetirement;
	}

	public void setReasonRetirement(String reasonRetirement) {
		this.reasonRetirement = reasonRetirement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workers")
	public Set<Vacations> getVacationses() {
		return this.vacationses;
	}

	public void setVacationses(Set<Vacations> vacationses) {
		this.vacationses = vacationses;
	}

}
